"""
THESEUS Real Rocket and Spacecraft Presets Catalog.
All specifications are sourced from official agency specifications and technical manuals.
Values are categorized into Launch Vehicles, Spacecraft / Upper Stages, and Payloads.
"""

from typing import List, Dict, Any

ROCKET_PRESETS: List[Dict[str, Any]] = [
    # -----------------------------------------------------------------------
    # SPACECRAFT & UPPER STAGES (Used for in-orbit & interplanetary burns)
    # -----------------------------------------------------------------------
    {
        "id": "isro-chandrayaan-pm",
        "name": "ISRO Chandrayaan-3 Propulsion Module",
        "operator": "ISRO",
        "category": "Spacecraft / Propulsion Module",
        "stages": 1,
        "dry_mass_kg": 448.0,
        "propellant_mass_kg": 1696.0,
        "max_thrust_n": 440.0,
        "specific_impulse_s": 300.0,
        "cross_section_area_m2": 4.5,
        "drag_coefficient": 2.2,
        "reflectivity_coefficient": 1.4,
        "confidence": "Authoritative Reference (ISRO Mission Dossier)",
        "citation": "ISRO Chandrayaan-3 Mission Specification / isro.gov.in",
        "description": "Propulsion module that transported the Vikram lander and Pragyan rover to a 100 km lunar orbit using a 440 N liquid bi-propellant engine.",
        "sprite_id": "chandrayaan",
    },
    {
        "id": "nasa-apollo-csm",
        "name": "NASA Apollo CSM (Service Module)",
        "operator": "NASA",
        "category": "Spacecraft / Crew Vehicle",
        "stages": 1,
        "dry_mass_kg": 5500.0,
        "propellant_mass_kg": 18410.0,
        "max_thrust_n": 91200.0,
        "specific_impulse_s": 314.0,
        "cross_section_area_m2": 12.0,
        "drag_coefficient": 2.2,
        "reflectivity_coefficient": 1.5,
        "confidence": "Authoritative Reference (NASA SP-4029)",
        "citation": "Apollo Operations Handbook SM 2A-03-S / NASA",
        "description": "Apollo Service Module powered by the AJ10-137 engine. Provided lunar orbit insertion, plane changes, and trans-Earth injection maneuvers.",
        "sprite_id": "apollo",
    },
    {
        "id": "spacex-dragon-trunk",
        "name": "SpaceX Dragon 2 / SuperDraco Stack",
        "operator": "SpaceX",
        "category": "Spacecraft / Orbital Capsule",
        "stages": 1,
        "dry_mass_kg": 6000.0,
        "propellant_mass_kg": 1388.0,
        "max_thrust_n": 1600.0,
        "specific_impulse_s": 300.0,
        "cross_section_area_m2": 9.6,
        "drag_coefficient": 2.2,
        "reflectivity_coefficient": 1.4,
        "confidence": "Authoritative Reference (SpaceX Falcon/Dragon Guide)",
        "citation": "SpaceX Crew Dragon Operational Profile / NASA ISS Multilateral Crew",
        "description": "Autonomous orbital rendezvous and docking vehicle equipped with Draco hypergolic thrusters for ISS proximity maneuvers.",
        "sprite_id": "dragon",
    },
    {
        "id": "deep-space-chemical",
        "name": "Deep Space Chemical Explorer (Generic)",
        "operator": "International Space Science Stack",
        "category": "Interplanetary Spacecraft",
        "stages": 1,
        "dry_mass_kg": 850.0,
        "propellant_mass_kg": 1400.0,
        "max_thrust_n": 450.0,
        "specific_impulse_s": 325.0,
        "cross_section_area_m2": 5.0,
        "drag_coefficient": 2.2,
        "reflectivity_coefficient": 1.4,
        "confidence": "Engineering Model (JPL/ESA Standard Bus)",
        "citation": "AIAA Spacecraft Design Handbook",
        "description": "Representative planetary exploration spacecraft equipped with high-efficiency bipropellant propulsion for orbit insertion and flybys.",
        "sprite_id": "probe",
    },
    {
        "id": "deep-space-ion",
        "name": "Deep Space Solar Electric / Ion Propulsion",
        "operator": "Deep Space Research",
        "category": "Ion Propulsion Stage",
        "stages": 1,
        "dry_mass_kg": 450.0,
        "propellant_mass_kg": 150.0,
        "max_thrust_n": 0.25,
        "specific_impulse_s": 3100.0,
        "cross_section_area_m2": 15.0,
        "drag_coefficient": 2.2,
        "reflectivity_coefficient": 1.7,
        "confidence": "Authoritative Reference (NASA Dawn/Deep Space 1)",
        "citation": "NASA NSTAR Gridded Ion Thruster Technical Report",
        "description": "Ultra-high specific impulse Xenon electrostatic ion propulsion providing massive Δv over extended low-thrust burns.",
        "sprite_id": "ion",
    },
    {
        "id": "voyager-probe",
        "name": "Voyager 1 Interplanetary Spacecraft",
        "operator": "NASA / JPL",
        "category": "Interplanetary Spacecraft",
        "stages": 1,
        "dry_mass_kg": 722.0,
        "propellant_mass_kg": 104.0,
        "max_thrust_n": 0.89,
        "specific_impulse_s": 230.0,
        "cross_section_area_m2": 10.75,
        "drag_coefficient": 2.2,
        "reflectivity_coefficient": 1.5,
        "confidence": "Authoritative Reference (NASA JPL)",
        "citation": "JPL Voyager Mission Operations Manual",
        "description": "Historical outer-planets probe propelled by hydrazine thrusters and RTG power, currently traversing interstellar space.",
        "sprite_id": "voyager",
    },

    # -----------------------------------------------------------------------
    # LAUNCH VEHICLES (Used for booster liftoff & staging reference)
    # -----------------------------------------------------------------------
    {
        "id": "isro-pslv-xl",
        "name": "ISRO PSLV-XL",
        "operator": "ISRO",
        "category": "Launch Vehicle (4-Stage)",
        "stages": 4,
        "dry_mass_kg": 28000.0,
        "propellant_mass_kg": 292000.0,
        "payload_leo_kg": 3800.0,
        "payload_gto_kg": 1425.0,
        "max_thrust_n": 4800000.0,
        "specific_impulse_s": 430.0,
        "cross_section_area_m2": 7.07,
        "drag_coefficient": 0.35,
        "reflectivity_coefficient": 1.4,
        "confidence": "Authoritative Reference (ISRO)",
        "citation": "ISRO PSLV Launch Vehicle Manual",
        "description": "ISRO's workhorse orbital launch vehicle that successfully dispatched Chandrayaan-1 and Mars Orbiter Mission.",
        "sprite_id": "pslv",
    },
    {
        "id": "isro-lvm3",
        "name": "ISRO LVM3 (Chandrayaan-3 Launcher)",
        "operator": "ISRO",
        "category": "Launch Vehicle (3-Stage Heavy)",
        "stages": 3,
        "dry_mass_kg": 48000.0,
        "propellant_mass_kg": 592000.0,
        "payload_leo_kg": 10000.0,
        "payload_gto_kg": 4000.0,
        "max_thrust_n": 9800000.0,
        "specific_impulse_s": 453.0,
        "cross_section_area_m2": 19.63,
        "drag_coefficient": 0.38,
        "reflectivity_coefficient": 1.4,
        "confidence": "Authoritative Reference (ISRO)",
        "citation": "ISRO LVM3 Payload Fairing & Mission Manual",
        "description": "ISRO's heaviest operational launch vehicle, propelled by two S200 solid strap-ons, L110 core, and C25 cryogenic upper stage.",
        "sprite_id": "lvm3",
    },
    {
        "id": "spacex-falcon9",
        "name": "SpaceX Falcon 9 (Block 5)",
        "operator": "SpaceX",
        "category": "Launch Vehicle (2-Stage Reusable)",
        "stages": 2,
        "dry_mass_kg": 25600.0,
        "propellant_mass_kg": 520000.0,
        "payload_leo_kg": 22800.0,
        "payload_gto_kg": 8300.0,
        "max_thrust_n": 7607000.0,
        "specific_impulse_s": 348.0,
        "cross_section_area_m2": 10.75,
        "drag_coefficient": 0.36,
        "reflectivity_coefficient": 1.4,
        "confidence": "Authoritative Reference (SpaceX)",
        "citation": "SpaceX Falcon 9 Launch Vehicle User's Guide",
        "description": "Two-stage orbital rocket powered by 9 Merlin-1D liquid oxygen / RP-1 engines with re-entry and landing capability.",
        "sprite_id": "falcon9",
    },
    {
        "id": "nasa-saturn-v",
        "name": "NASA Saturn V",
        "operator": "NASA",
        "category": "Super Heavy Launch Vehicle (3-Stage)",
        "stages": 3,
        "dry_mass_kg": 130000.0,
        "propellant_mass_kg": 2840000.0,
        "payload_leo_kg": 140000.0,
        "payload_gto_kg": 43500.0,
        "max_thrust_n": 34500000.0,
        "specific_impulse_s": 421.0,
        "cross_section_area_m2": 80.1,
        "drag_coefficient": 0.42,
        "reflectivity_coefficient": 1.5,
        "confidence": "Authoritative Reference (NASA SP-4029)",
        "citation": "NASA Saturn Illustrated Chronology",
        "description": "Historic super heavy launcher that launched the Apollo lunar landing expeditions.",
        "sprite_id": "saturn5",
    },
]
